version: '3.2'
services:
  bugbug-base:
    build:
      context: .
      dockerfile: infra/dockerfile.base
    image: mozilla/bugbug-base

  bugbug-http-service:
    build:
      context: http_service
    image: mozilla/bugbug-http-service
    environment:
      - BUGBUG_BUGZILLA_TOKEN
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host